#!/bin/bash

echo "Triger received. Deploying..."
cd /opt/blueblood
git --git-dir=/opt/blueblood.git --work-tree=/opt/blueblood checkout master -f

echo 'Installing'
npm install

echo 'Building...'
PORT=3064 npm run build

echo 'Starting server.' 
PORT=3064 pm2 start ./index.js --name blueblood
