#!/bin/bash

read_var() {
    VAR=$(grep $1 $2 | xargs)
    IFS="=" read -ra VAR <<< "$VAR"
    echo ${VAR[1]#*=}
}

APP_NAME=$(read_var APP_NAME /root/.scripts/.env)
PORT=$(read_var PROD_PORT /root/.scripts/.env)

echo "Triger received. Deploying..."
cd /opt/blueblood
git --git-dir=/opt/blueblood.git --work-tree=/opt/blueblood checkout master -f

echo 'Installing'
npm install

echo 'Building...'
PORT=$PORT npm run build

echo 'Starting server.' 
if [ "$(pm2 id $APP_NAME) "= "[]" ]; then
  pm2 start ./index.js --name "$APP_NAME" -i max
else
  pm2 reload "$APP_NAME"
fi
